# serverless.yml
service: lambda-selenium

package:
  artifact: build/libs/lambda-selenium-all.jar

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: java8
  memorySize: 3008
  timeout: 300
  versionFunctions: false

functions:
  'lambda-selenium-pwc-function':
    handler: 'com.pwc.testing.lambda.LambdaTestHandler::handleRequest'
    name: lambda-selenium-pwc-function
    description: Lambda Selenium Demo Tests
